# Generated by Django 2.1.5 on 2019-02-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grammarcheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grammarcheckhistory',
            options={'verbose_name': 'Grammar Check History', 'verbose_name_plural': 'Grammar Check Histories'},
        ),
    ]
