# Generated by Django 2.1.5 on 2019-02-06 12:13

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wordcounter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcounterhistory',
            name='_picked_obj',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
